{"stats": {"errors": 0, "failures": 2, "passes": 8, "skipped": 0, "encoding": "UTF-8", "total": 10}, "results": [{"classname": "index_test:TestDictionary", "name": "test_area", "time": 0.00023102760314941406, "type": "success"}, {"classname": "index_test:TestDictionary", "name": "test_change_spelling", "time": 0.00013589859008789062, "type": "success"}, {"classname": "index_test:TestDictionary", "name": "test_city_count", "time": 0.00014972686767578125, "type": "success"}, {"classname": "index_test:TestDictionary", "name": "test_city_keys", "time": 0.0002040863037109375, "type": "success"}, {"classname": "index_test:TestDictionary", "name": "test_city_values", "time": 0.0001347064971923828, "type": "success"}, {"classname": "index_test:TestDictionary", "name": "test_greenville_population", "time": 0.00010466575622558594, "type": "success"}, {"classname": "index_test:TestDictionary", "name": "test_los_cabos_pop", "time": 9.799003601074219e-05, "type": "success"}, {"classname": "index_test:TestDictionary", "name": "test_pyeongchang_keys", "time": 0.0004703998565673828, "type": "failure", "errtype": "builtins.AssertionError", "message": "<class 'dict_keys'> != <class 'list'>", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 67, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 625, in run\n    testMethod()\n  File \"/home/yoyothesheep/python-dictionaries-lab-data-science-alpha/test/index_test.py\", line 31, in test_pyeongchang_keys\n    self.assertEqual(type(pyeongchang_keys), type(list()))\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 836, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 829, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: <class 'dict_keys'> != <class 'list'>\n"}, {"classname": "index_test:TestDictionary", "name": "test_pyeongchang_values", "time": 0.00031304359436035156, "type": "failure", "errtype": "builtins.AssertionError", "message": "<class 'dict_values'> != <class 'list'>", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 67, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 625, in run\n    testMethod()\n  File \"/home/yoyothesheep/python-dictionaries-lab-data-science-alpha/test/index_test.py\", line 35, in test_pyeongchang_values\n    self.assertEqual(type(pyeongchang_values), type(list()))\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 836, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 829, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: <class 'dict_values'> != <class 'list'>\n"}, {"classname": "index_test:TestDictionary", "name": "test_salina", "time": 0.0001499652862548828, "type": "success"}]}